[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Hack Nerd Font Mono"
style = "Medium"

[font.offset]
y = 2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.95

[window.dimensions]
columns = 123
lines = 38

# Colors (Snazzy)
[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text = "#282a36"
background = "#feffff"

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.bright]
black = "#686868"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#eff0eb"

