[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "MonoLisa Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/home/linuxbrew/.linuxbrew/bin/zsh"

[window]
opacity = 0.9

[window.dimensions]
columns = 123

lines = 45

[colors.primary]
background = "#001419"
foreground = "0x839496"

[colors.normal]
black = "0x073642"
red = "0xdc322f"
green = "0x859900"
yellow = "0xb58900"
blue = "0x268bd2"
magenta = "0xd33682"
cyan = "0x2aa198"
white = "0xeee8d5"

[colors.bright]
black = "0x002b36"
red = "0xcb4b16"
green = "0x586e75"
yellow = "0x657b83"
blue = "0x839496"
magenta = "0x6c71c4"
cyan = "0x93a1a1"
white = "0xfdf6e3"
