[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.offset]
y = 2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9

[window.dimensions]
columns = 123
lines = 38

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
