[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.offset]
y = 2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9

[window.dimensions]
columns = 123
lines = 38

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
