[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# [font.offset]
# y = 1

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/bin/zsh"

[window]
opacity = 1

[window.dimensions]
columns = 120
lines = 30

[colors.primary]
background = "#1f1e2f"
foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
bright_foreground = "#CAD3F5"

[colors.cursor]
text = "#1f1e2f"
cursor = "#F4DBD6"

[colors.vi_mode_cursor]
text = "#1f1e2f"
cursor = "#B7BDF8"

[colors.search.matches]
foreground = "#1f1e2f"
background = "#A5ADCB"

[colors.search.focused_match]
foreground = "#1f1e2f"
background = "#A6DA95"

[colors.footer_bar]
foreground = "#1f1e2f"
background = "#A5ADCB"

[colors.hints.start]
foreground = "#1f1e2f"
background = "#EED49F"

[colors.hints.end]
foreground = "#1f1e2f"
background = "#A5ADCB"

[colors.selection]
text = "#1f1e2f"
background = "#F4DBD6"

[colors.normal]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[colors.bright]
black = "#5B6078"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#A5ADCB"

[colors.dim]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[[colors.indexed_colors]]
index = 16
color = "#F5A97F"

[[colors.indexed_colors]]
index = 17
color = "#F4DBD6"
