# Disable the blank line at the start of the prompt
add_newline = false

[git_branch]
symbol = " "

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:green)'
error_symbol = '[ ](bold fg:red)'
vimcmd_symbol = '[ ](bold fg:green)'
vimcmd_replace_one_symbol = '[ ](bold fg:lavender)'
vimcmd_replace_symbol = '[ ](bold fg:lavender)'
vimcmd_visual_symbol = '[ ](bold fg:yellow)'
